Add Go 1.3 and drop Go 1.1
Capstan depdencency no longer builds with Go 1.1:

../../../gopkg.in/yaml.v1/encode.go:188: undefined: strings.IndexByte
../../../gopkg.in/yaml.v1/encode.go:188: undefined: strings.IndexByte

While at it, add Go 1.3.

Signed-off-by: Pekka Enberg <penberg@cloudius-systems.com>